apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: Zone
metadata:
  name: example-com-zone 
spec:
  forProvider:
    name: example.com
    paused: true
    jumpStart: false
    settings:
      developmentMode: true
  providerConfigRef:
    name: example